# Generated by Django 4.2.30 on 2026-04-26 15:01

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('merchant', 'Merchant')], default='farmer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('land_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_tamil', models.CharField(blank=True, max_length=100)),
                ('emoji', models.CharField(default='🌱', max_length=10)),
                ('category', models.CharField(choices=[('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('grain', 'Grain'), ('cash', 'Cash Crop'), ('spice', 'Spice')], max_length=20)),
                ('season', models.CharField(choices=[('kharif', 'Kharif (Jun–Nov)'), ('rabi', 'Rabi (Nov–Apr)'), ('zaid', 'Zaid (Apr–Jun)'), ('annual', 'Annual')], max_length=20)),
                ('duration_days', models.TextField()),
                ('water_req', models.TextField()),
                ('temp_range', models.TextField()),
                ('soil_type', models.TextField()),
                ('ph_range', models.CharField(max_length=50)),
                ('yield_per_ha', models.TextField()),
                ('market_price', models.TextField()),
                ('description', models.TextField()),
                ('description_tamil', models.TextField(blank=True)),
                ('suitable_districts', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_tamil', models.CharField(blank=True, max_length=200)),
                ('ftype', models.CharField(choices=[('organic', 'Organic'), ('inorganic', 'Inorganic'), ('bio', 'Bio-Fertilizer'), ('npk', 'NPK Complex')], max_length=20)),
                ('npk_ratio', models.CharField(blank=True, max_length=100)),
                ('dosage', models.TextField()),
                ('suitable_crops', models.TextField()),
                ('application', models.TextField()),
                ('benefits', models.TextField()),
                ('price_range', models.CharField(max_length=200)),
                ('emoji', models.CharField(default='🧪', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LearnContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_tamil', models.CharField(blank=True, max_length=200)),
                ('ctype', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('guide', 'Guide')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('description', models.TextField()),
                ('emoji', models.CharField(default='📚', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LoanScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=300)),
                ('emoji', models.CharField(default='🏦', max_length=10)),
                ('min_amount', models.CharField(max_length=200)),
                ('max_amount', models.CharField(max_length=200)),
                ('interest_rate', models.TextField()),
                ('repayment', models.TextField()),
                ('eligibility', models.TextField()),
                ('documents', models.TextField()),
                ('benefits', models.TextField()),
                ('how_to_apply', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MandiPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('emoji', models.CharField(default='🌾', max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('modal_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('stable', 'Stable')], default='stable', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ptype', models.CharField(choices=[('insecticide', 'Insecticide'), ('fungicide', 'Fungicide'), ('herbicide', 'Herbicide'), ('organic', 'Organic')], max_length=20)),
                ('active_ingredient', models.TextField()),
                ('target_pests', models.TextField()),
                ('dosage', models.TextField()),
                ('safety_interval', models.TextField()),
                ('precautions', models.TextField()),
                ('is_organic', models.BooleanField(default=False)),
                ('emoji', models.CharField(default='🛡️', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestingGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maturity_signs', models.TextField()),
                ('harvest_method', models.TextField()),
                ('post_harvest', models.TextField()),
                ('storage_tips', models.TextField()),
                ('best_time', models.TextField()),
                ('shelf_life', models.TextField()),
                ('crop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harvest', to='agro_site.crop')),
            ],
        ),
        migrations.CreateModel(
            name='FarmDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dtype', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.TextField()),
                ('yield_info', models.TextField()),
                ('specialty', models.TextField()),
                ('released_by', models.CharField(blank=True, max_length=200)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='agro_site.crop')),
            ],
        ),
        migrations.CreateModel(
            name='CropDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_tamil', models.CharField(blank=True, max_length=200)),
                ('symptoms', models.TextField()),
                ('treatment', models.TextField()),
                ('prevention', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='agro_site.crop')),
            ],
        ),
    ]
